modLoader="javafml"
loaderVersion = "[1,)"
license="${license}"
issueTrackerURL = "${issues_url}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL = "${sources_url}"
logoFile="${mod_id}_icon.png"
logoBlur=false
authors="${mod_author}"
description='''
${description}
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange = "${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="caelus"
    mandatory=true
    versionRange="${caelus_version_range}"
    ordering="NONE"
    side="BOTH"
